Active customer
mouniamekrane/customerData pull request #2
Opened 2022-01-10 01:52 UTC by mouniamekrane

working on active customer

2022-01-10 07:55 UTC, faouzioudouh requested changes
You are missing a lot, I couldn't understand your code or what you are trying to achieve :)

2022-01-10 07:55 UTC, faouzioudouh commented on src/Footer/footer.js
> +const clients = [{
Why are you copying cutomers here?

2022-01-10 07:55 UTC, faouzioudouh commented on src/Footer/ActiveClients/activeClients.js
> +export const CountActive = ({ clientsToCount }) => {
What is this? component? function?

2022-01-11 04:19 UTC, merged

2022-01-11 04:40 UTC, mouniamekrane commented on src/Footer/ActiveClients/activeClients.js
> +export const CountActive = ({ clientsToCount }) => {
its a component

2022-01-11 04:41 UTC, mouniamekrane commented on src/Footer/footer.js
> +const clients = [{
i did a mistake here